### ISSUE TITLE
PKG not installing

### ISSUE THREAD

**Issue by JonathanVeg0521** [florinsdistortedvision/OMSK-Retail-PKG-Installer#1]
I have done everything and when I start omsk daemon it gives me the error and then I plug my usb in. But the Pkg does not start installing

**Comment by Kvmeri** [comment]
Same thing. Not installing

**Comment by MrDuck2112** [comment]
For me it just says cannot start application...

**Comment by florinsdistortedvision** [comment]
Not working could mean a lot of reasons, such as:
- The file structure of your install USB is wrong.
- The packages you are trying to install are not retail. FPKGs such as pirated games you can find online will not install as the system doesn't recognize them without a jailbreak.
- The packages might be merged if updates. 
- Some packages might need a JSON file as well like in the case of PT.

Without any reasons or steps to reproduce I cannot determine why it's not working for you.
